# Generated by Django 5.2.4 on 2025-08-02 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management_system_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='priority',
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('to_do', 'To Do'), ('in_progress', 'In Progress'), ('done', 'Done')], default='to_do', max_length=20),
        ),
    ]
